// Map of country names to their corresponding flag emojis
export const COUNTRY_FLAGS: Record<string, string> = {
  'Japan': '🇯🇵',
  'France': '🇫🇷',
  'USA': '🇺🇸',
  'UAE': '🇦🇪',
  'Australia': '🇦🇺',
  'Vietnam': '🇻🇳',
  'South Korea': '🇰🇷',
  'Thailand': '🇹🇭',
  'India': '🇮🇳',
  'Taiwan': '🇹🇼',
  'Laos': '🇱🇦',
  'Portugal': '🇵🇹',
  'Scotland': '🇬🇧',
  'Slovenia': '🇸🇮',
  'Croatia': '🇭🇷',
  'Norway': '🇳🇴',
  'Austria': '🇦🇹',
  'Belgium': '🇧🇪',
  'South Africa': '🇿🇦',
  'Morocco': '🇲🇦',
  'Zanzibar': '🇹🇿',
  'Egypt': '🇪🇬',
  'Zimbabwe': '🇿🇼',
  'Peru': '🇵🇪',
  'Colombia': '🇨🇴',
  'Canada': '🇨🇦',
  'Mexico': '🇲🇽',
  'Uruguay': '🇺🇾',
  'Turkey': '🇹🇷',
  'Jordan': '🇯🇴',
  'Oman': '🇴🇲',
  'New Zealand': '🇳🇿',
  'Samoa': '🇼🇸',
  'Iceland': '🇮🇸',
  'Chile': '🇨🇱',
  'Brazil': '🇧🇷',
  'Guatemala': '🇬🇹',
  'Estonia': '🇪🇪',
  'Bosnia and Herzegovina': '🇧🇦',
  'Georgia': '🇬🇪',
  'Bulgaria': '🇧🇬',
  'Montenegro': '🇲🇪',
  'Czech Republic': '🇨🇿',
  'Myanmar': '🇲🇲'
};

export function getCountryFlag(country: string): string {
  return COUNTRY_FLAGS[country] || '🏳️';
}